replicaCount: 1
arkServerPasswordSecretName: ark-server-password
arkServerAdminPasswordSecretName: ark-server-password
serverConfig:
  arkServerName: An Ark Server
  sessionName: An Ark Session
  serverMap: TheIsland
  maxPlayers: 10
  updateOnStart: true
  backupOnStop: true
  preUpdateBackup: true
  warnOnStop: true
  mods: []
    # id: 1234567
    # state: <game|disabled>
gameConfig: {}
gameUserSettingsConfig:
  ServerSettings:
    allowThirdPersonPlayer: false
    AllowCaveBuildingPvE: false
    alwaysNotifyPlayerJoined: false
    alwaysNotifyPlayerLeft: false
    bAllowFlyerCarryPvE: false
    bDisableStructureDecayPvE: false
    DayCycleSpeedScale: 1
    DayTimeSpeedScale: 1
    NightTimeSpeedScale: 1
    DinoCharacterFoodDrainMultiplier: 1
    DinoCharacterHealthRecoveryMultiplier: 1
    DinoCharacterStaminaDrainMultiplier: 1
    DinoCountMultiplier: 1
    DinoDamageMultiplier: 1
    DinoResistanceMultiplier: 1
    globalVoiceChat: false
    HarvestAmountMultiplier: 1
    HarvestHealthMultiplier: 1
    MaxStructuresInRange: 6700
    noTributeDownloads: false
    PreventDownloadSurvivors: false
    PreventDownloadItems: false
    PreventDownloadDinos: false
    PlayerCharacterFoodDrainMultiplier: 1
    PlayerCharacterHealthRecoveryMultiplier: 1
    PlayerCharacterStaminaDrainMultiplier: 1
    PlayerCharacterWaterDrainMultiplier: 1
    PlayerDamageMultiplier: 1
    PlayerResistanceMultiplier: 1
    proximityChat: false
    ResourceNoReplenishRadiusPlayers: 1
    ResourceNoReplenishRadiusStructures: 1
    ResourcesRespawnPeriodMultiplier: 1
    ServerCrosshair: false
    serverForceNoHud: false
    serverHardcore: false
    serverPVE: false
    ShowMapPlayerLocation: false
    StructureDamageMultiplier: 1
    StructureResistanceMultiplier: 1
    TamedDinoDamageMultiplier: 1
    TamedDinoResistanceMultiplier: 1
    TamingSpeedMultiplier: 1
    XPMultiplier: 1
    EnablePVPGamma: false
    EnablePVEGamma: false
    SpectatorPassword: ''
    DifficultyOffset: 0.5
    PvEStructureDecayPeriodMultiplier: 1
    PvEStructureDecayDestructionPeriod: 1
    Banlist: 'http://arkdedicated.com/banlist.txt'
    PvPStructureDecay: false
    DisableDinoDecayPvE: false
    PvEDinoDecayPeriodMultiplier: 1
    AdminLogging: false
    MaxTamedDinos: 8000
    MaxNumbersofPlayersInTribe: 2
    BattleNumOfTribestoStartGame: 2
    TimeToCollapseROD: 100
    BattleAutoStartGameInterval: 100
    BattleSuddenDeathInterval: 300
    KickIdlePlayersPeriod: 1800
    PerPlatformMaxStructuresMultiplier: 1
    StructureDamageRepairCooldown: 180
    bForceAllStructureLocking: true
    AutoDestroyOldStructuresMultiplier: 0
    bUseVSync: false
    MaxPlatformSaddleStructureLimit: 100
    bPassiveDefensesDamageRiderlessDinos: true
    AutoSavePeriodMinutes: 20
    RCONServerGameLogBuffer: 600
    OverrideStructurePlatformPrevention: false
    PreventOfflinePvPInterval: 60
    bPvPDinoDecay: true
    bPvPStructureDecay: true
    DisableImprintDinoBuff: true
    AllowAnyoneBabyImprintCuddle: true
    EnableExtraStructurePreventionVolumes: true
    ShowFloatingDamageText: true
    DestroyUnconnectedWaterPipes: false
    OverrideOfficialDifficulty: 1
    TheMaxStructuresInRange: 10500
    MinimumDinoReuploadInterval: 0
    PvEAllowStructuresAtSupplyDrops: false
    NPCNetworkStasisRangeScalePlayerCountStart: 70
    NPCNetworkStasisRangeScalePlayerCountEnd: 120
    NPCNetworkStasisRangeScalePercentEnd: 0.5
    MaxPersonalTamedDinos: 500
    AutoDestroyDecayedDinos: true
    ClampItemSpoilingTimes: false
    UseOptimizedHarvestingHealth: true
    AllowCrateSpawnsOnTopOfStructures: true
    ForceFlyerExplosives: false
    PreventOfflinePvP: true
    AllowFlyingStaminaRecovery: true
    AllowMultipleAttachedC4: true
    OxygenSwimSpeedStatMultiplier: 1
    bPvEDisableFriendlyFire: false
    ServerAutoForceRespawnWildDinosInterval: 86400
    DisableWeatherFog: false
    RandomSupplyCratePoints: false
    CrossARKAllowForeignDinoDownloads: false
    PersonalTamedDinosSaddleStructureCost: 19
  /script/engine.gamesession:
    MaxPlayers: 10
  SessionSettings: {}
  MessageOfTheDay:
    Duration: 30
    Message: Welcome to my Ark Server!

persistence:
  size: 10Gi
ports:
  rcon: 27020
  query: 27015
  game: 7777
  gameExt: 7778
resources:
  requests:
    memory: 4Gi
    cpu: 1
  limits:
    memory: 8Gi
    cpu: 3