webfacade:
  image: hobart2967/lea-etienne-photos-api:latest
  storageSize: 40Gi
  storage:
    mountPath: /usr/share/image-api-server/.storage
  extraMounts:
    - name: api-configuration-json
      mountPath: /usr/share/image-api-server/configuration.json
      sourcePath: configuration.json
      configMap:
        name: api-configuration-json
        items:
        - key: "content"
          path: "configuration.json"
          mode: 0644
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  ports:
    - name: api
      containerPort: 4711
rules:
  - name: api
    condition: "Host(`leaetienne.codewyre.net`) && PathPrefix(`/api`)"
    priority: 100
    middlewares:
      - name: strip-api-prefix
    services:
      - name: api
        port: api
