databases:
  - resourceName: wedding-db
    name: wedding_db
users:
  - name: leaetienne
    host: "%" # Needs to be the host from where the client logs in.
    databases:
      - name: wedding_db
        host: "%"
        privileges:
        - "ALL PRIVILEGES"

