environments:
  sidra:
    values:
      - hostIp: 192.168.178.103
        hostNickname: sidra
        secretVault: 64iqhopdnz56fpxgk5mr3uhqpe
        secretsMap:
          roundcube-db-roundcube:
            item: lihea4hqnnqbyics2kcizfrabm
            namespaces:
              - project-engineer-marcoklein
            fields:
              - password
          acme-pebble-tls:
            item: mboadzgvwvch6pwjs7vokhrrc4
            fields:
              - crt
              - key
            namespaces:
              - sys-acme
          acme-pebble-ca:
            item: mboadzgvwvch6pwjs7vokhrrc4
            fields:
              - crt
            namespaces:
              - sys-traefik
          storage-box-1:
            item: abx7ycy2tfb7ppeeqnknatgfsy
            fields:
              - username
              - password
              - domain
            namespaces:
              - kube-system
          crowdsec-bouncer-key:
            item: tejriu4qqc7lpvgnyrcthe3r2y
            namespaces:
              - sys-crowdsec
            fields:
              - api-key
          ntfy-grafana:
            item: ny72nqjed4wz6rfflxj2ihi7ym
            namespaces:
              - sys-ntfy
              - monitoring
            fields:
              - username
              - password
              - role
              - access_token
            extras:
              topics:
                - server_alerts:rw
            annotations:
              hobart2967.github.io/ntfy-token: "true"
              hobart2967.github.io/ntfy-user: "true"
          ntfy-homeserver:
            item: ppn6pbuljlrsslxzr3a4v57x2a
            namespaces:
              - sys-ntfy
            fields:
              - username
              - password
              - access_token
              - role
            extras:
              topics:
                - backups:rw
                - homeserver-alerts:rw
            annotations:
              hobart2967.github.io/ntfy-token: "true"
              hobart2967.github.io/ntfy-user: "true"
          ntfy-hobart:
            item: udy2dgh2pr2otc5ov5nqq5q3pi
            namespaces:
              - sys-ntfy
            fields:
              - username
              - password
              - role
            annotations:
              hobart2967.github.io/ntfy-user: "true"
          grafana-admin:
            item: 5cctdss53axmrc67inrtrwozw4
            namespaces:
              - monitoring
            fields:
              - password
              #- name
              - username
              #- email
          de-avsn-maps:
            item: m76m4hps4kzxttc6jnnojvlgvq
            namespaces:
              - project-minecraft-avsn
            fields:
              - password
          cloud-codewyre-net:
            item: sgbtrn2w7fm5sv6vqvk4mjr35m
            namespaces:
              - sys-localstack
            fields:
              - username
              - password
          de-avsn-mariadb-root:
            item: 44djwk4bbnnhn7b3vvngkgs34y
            namespaces:
              - project-de-avsn
            fields:
              - password
          database-web1:
            item: 2kwhr2kdmghidhbk4gcviqnt7e
            namespaces:
              - project-de-avsn
            fields:
              - password
          ark-server-password:
            item: rwvbvxet7zoeodrj5pzbwhrc2a
            namespaces:
              - project-ark
            fields:
              - admin_password
              - password
          home-server-bastion:
            item: null
            namespaces:
              - project-backup
            fields:
              - ip_address
              - username
              - password
          home-server:
            item: null
            namespaces:
              - project-home-server
            fields:
              - mac_address
          vpn:
            item: null
            namespaces:
              - project-vpn
            fields:
              - portal
              - ipsec_key
              - username
              - password
              - ipsec_id
          net-codewyre-ela-micha:
            item: null
            namespaces:
              - project-elamicha
            fields:
              - password
              - db_password
          net-codewyre-leaetienne:
            item: null
            namespaces:
              - project-wedding-leaetienne
            fields:
              - password
          database-leaetienne:
            item: null
            namespaces:
              - project-wedding-leaetienne
            fields:
              - password

  tharja:
    values:
      - hostIp: 78.46.47.87
        hostNickname: tharja
        secretVault: ha34ot6ty3cy4rkp54jgvdluae
        secretsMap:
          admin-user:
            item: xrlg7kwckl6lpuplpt4scutfyu
            namespaces:
              - sys-docker-registry
            fields:
              - username
              - password
          crowdsec-ui:
            item: 3satfjh3ug7wxlfnjg2eultuwm
            namespaces:
              - sys-crowdsec
            fields:
              - password
          roundcube-db-roundcube:
            item: ws3w6g5bii4ajcd6hif7se2zay
            namespaces:
              - project-engineer-marcoklein
            fields:
              - password
          storage-box-1:
            item: grlxfena23vjbdmdtepx7uik6e
            fields:
              - username
              - password
              - domain
            namespaces:
              - kube-system
          crowdsec-bouncer-key:
            item: lvhm6np2blx7l322efwetpapxi
            namespaces:
              - sys-crowdsec
            fields:
              - api-key
          ntfy-grafana:
            item: 2mocvryly44i63iq6c2ct36tcy
            namespaces:
              - sys-ntfy
              - monitoring
            fields:
              - username
              - password
              - role
              - access_token
            extras:
              topics:
                - server_alerts:rw
          ntfy-homeserver:
            item: 25he6rmdshpzetnkiggdqon6b4
            namespaces:
              - sys-ntfy
            fields:
              - username
              - password
              - access_token
              - role
            extras:
              topics:
                - backups:rw
                - homeserver-alerts:rw
            annotations:
              hobart2967.github.io/ntfy-token: "true"
              hobart2967.github.io/ntfy-user: "true"
          ntfy-hobart:
            item: wvarzykubx3z7arlc5itqx6dha
            namespaces:
              - sys-ntfy
            fields:
              - username
              - password
              - role
            annotations:
              hobart2967.github.io/ntfy-user: "true"
          grafana-admin:
            item: lalvtnegadzm2la2eeulxmhdni
            namespaces:
              - monitoring
            fields:
              - password
              - username
          de-avsn-maps:
            item: c5etbdq4uwawxvbinvlior5xba
            namespaces:
              - project-minecraft-avsn
            fields:
              - password
          cloud-codewyre-net:
            item: 22zwcewxzorho53x3tkpwe5jim
            namespaces:
              - sys-localstack
            fields:
              - username
              - password
          de-avsn-mariadb-root:
            item: p5ppm7v5d37qw3hsd27wwol4ee
            namespaces:
              - project-de-avsn
            fields:
              - password
          database-web1:
            item: 4zscr3qhm2zfd4ol4vvosmqkiq
            namespaces:
              - project-de-avsn
            fields:
              - password
          ark-server-password:
            item: mgqe2zbksqx7trviusnl4aggty
            namespaces:
              - project-ark
            fields:
              - admin_password
              - password
          home-server-bastion:
            item: syywokky6f4fj7dar74pvfrwlm
            namespaces:
              - project-backup
            fields:
              - ip_address
              - username
              - password
          home-server:
            item: syywokky6f4fj7dar74pvfrwlm
            namespaces:
              - project-home-server
            fields:
              - mac_address
          vpn:
            item: ma2s36bx6szayoymvyu7hzoxaa
            namespaces:
              - project-vpn
            fields:
              - portal
              - ipsec_key
              - username
              - password
              - ipsec_id
          net-codewyre-elamicha:
            item: ugdxxh7kjvlbzqxpwul546eqpi
            namespaces:
              - project-elamicha
            fields:
              - password
              - db_password
          net-codewyre-leaetienne:
            item: 7pioejaidd7bfcshg2kltqzc7e
            namespaces:
              - project-wedding-leaetienne
            fields:
              - password
          database-leaetienne:
            item: orhmtwr5e4xviedkvreuqbdivq
            namespaces:
              - project-wedding-leaetienne
            fields:
              - password
