---
helmDefaults:
  timeout: 600
  waitForJobs: true
  wait: true

helmfiles:
  - path: ./helmfiles/crds-bindy/helmfile.yaml
  - path: ./helmfiles/crds-monitoring/helmfile.yaml
  - path: ./helmfiles/crds-mariadb/helmfile.yaml
  - path: ./helmfiles/crds-traefik/helmfile.yaml

  - path: ./helmfiles/dns-system/helmfile.yaml
  - path: ./helmfiles/mariadb-system/helmfile.yaml
  - path: ./helmfiles/traefik-system/helmfile.yaml

  - path: ./helmfiles/dns-zones/helmfile.yaml

  - path: ./helmfiles/monitoring/helmfile.yaml

  - path: ./helmfiles/projects/de.avsn/helmfile.yaml
  - path: ./helmfiles/projects/engineer.marcoklein/helmfile.yaml
