---
repositories: []
releases:
  - name: prometheus-operator-crds
    namespace: default
    chart: prometheus-community/prometheus-operator-crds
    version: "27.0.1"
    installed: true

helmfiles:
  - path: ./helmfiles/crds-bindy/helmfile.yaml
  - path: ./helmfiles/crds-monitoring/helmfile.yaml

  - path: ./helmfiles/monitoring/helmfile.yaml
  - path: ./helmfiles/dns-system/helmfile.yaml
  - path: ./helmfiles/dns-cluste/helmfile.yaml

  - path: ./helmfiles/monitoring/helmfile.yaml
  - path: ./helmfiles/dns-zones/avsn.de/helmfile.yaml
  - path: ./helmfiles/dns-zones/adventurespiele.net/helmfile.yaml
  - path: ./helmfiles/projects/de.avsn/helmfile.yaml
