---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  {{ range .Values.webfacade.ports }}
  - name: {{ .name }}
    port: {{ .containerPort }}
    targetPort: {{ .containerPort }} {{- if .protocol }}
    protocol: {{ .protocol }} {{- end }}
  {{ end }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}


