---
helmDefaults:
  timeout: 600
  waitForJobs: true
  wait: true

helmfiles:
  - path: ./crds-bindy/helmfile.yaml.gotmpl
  - path: ./crds-monitoring/helmfile.yaml
  - path: ./crds-mariadb/helmfile.yaml
  - path: ./crds-cert-manager/helmfile.yaml
  - path: ./crds-traefik/helmfile.yaml
  - path: ./host-common/helmfile.yaml.gotmpl
  - path: ./sys-default/helmfile.yaml
  - path: ./sys-kube/helmfile.yaml
  - path: ./sys-dns/helmfile.yaml
  - path: ./sys-mariadb/helmfile.yaml
  - path: ./sys-mail/helmfile.yaml.gotmpl
  - path: ./sys-acme/helmfile.yaml.gotmpl
  - path: ./sys-cert-manager/helmfile.yaml
  - path: ./sys-traefik/helmfile.yaml
  - path: ./sys-crowdsec/helmfile.yaml.gotmpl
  - path: ./sys-storage/helmfile.yaml
  - path: ./sys-docker-registry/helmfile.yaml
  - path: ./sys-ntfy/helmfile.yaml.gotmpl

  - path: ./dns-zones/helmfile.yaml
  - path: ./monitoring/helmfile.yaml