---
repositories:
  - name: crowdsecurity
    url: https://crowdsecurity.github.io/helm-charts

releases:
  - name: sys-crowdsec
    namespace: sys-crowdsec
    createNamespace: true
    chart: ../../helm/project

  - name: crowdsec
    namespace: sys-crowdsec
    createNamespace: true
    needs:
      - sys-crowdsec
    chart: crowdsecurity/crowdsec
    version: 0.19.1
    values:
      - ./values/crowdsec.yaml

  - name: crowdsec-bouncer
    namespace: sys-crowdsec
    createNamespace: true
    needs:
      - crowdsec
    chart: ../../helm/crowdsec-bouncer
    hooks:
      - events: ["prepare", "presync"]
        showlogs: true
        command: sh
        args:
          - -ec
          - |
            ./bouncer-key.sh "{{`{{.Release.Namespace}}`}}"
    values:
      - ./.tmp/bouncer-key.yaml
      - lapiHost: crowdsec-service.sys-crowdsec.svc.cluster.local
        lapiPort: "8080"
        lapiScheme: http
        mode: ban
