databases:
  - resourceName: usr-web1-1
    name: usr_web1_1
users:
  - name: web1
    host: "%" # Needs to be the host from where the client logs in.
    databases:
      - name: usr_web1_1
        host: "%"
