webfacade:
  image: hobart2967/docker-apache2-php5.6.40
  storageSize: 500Gi
rules:
  - hostname:
      name: www
      zone: net-adventurespiele
    aliases:
    - name: "@"
      zone: net-adventurespiele
    - name: "@"
      zone: de-avsn
    - name: www
      zone: de-avsn
    services:
      - name: website
        port: http
