# domain
# tlsSecretName
databases: []
# - name: my-db
#
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

sqlJobs: []
# - name: init-schema
#   username: root
#   passwordSecretKeyRef:
#     name: database-root
#     key: MARIADB_ROOT_PASSWORD
#   database: my_db
#   sql: |
#     CREATE TABLE IF NOT EXISTS demo (
#       id INT PRIMARY KEY
#     );
