---
releases:
  - name: project
    namespace: project-engineer-marcoklein
    createNamespace: true
    chart: ../../helm/project

  - name: website
    chart: ../../helm/website
    namespace: project-engineer-marcoklein
    createNamespace: true
    values:
      - ./values/website.yaml
      - ./values/dns.yaml.gotmpl