---
{{- $serverConfig := .Values.serverConfig }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-banned-ips-json
  namespace: {{ .Release.Namespace }}
data:
  content: {{ $serverConfig.bannedIps | toJson }}
