---
{{- $serverConfig := .Values.serverConfig }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-spigot-yml
  namespace: {{ .Release.Namespace }}
data:
  content: {{ $serverConfig.spigot | toYaml | nindent 4 }}
