---

- hosts: all
  become: true
  become_method: sudo
  environment:
    PATH: "/usr/share/asdf/shims:/usr/share/asdf/bin:{{ lookup('env', 'PATH') }}"

  vars_files:
    - vars/defaults.yml
    - vars/{{ machine }}.yml

  tasks:
    - name: "Resolve secrets"
      include_tasks: tasks/secrets/task.yml
      when: secrets is defined

    # Debug secrets
    - name: "Debug secrets"
      debug:
        msg: "{{ secret_values }}"
    - name: Ground Zero
      include_tasks: tasks/ground-zero/task.yml
      when: provision.ground_zero

    - name: Setup Firewall and Fail2Ban
      include_tasks: tasks/security/task.yml
      when: provision.security

    # - name: Configure DNS
    #   include_tasks: tasks/dns/task.yml
    #   when: provision.dns

    # - name: Configure Certificates
    #   include_tasks: tasks/letsencrypt/task.yml
    #   when: provision.dns

    - name: Configure SSH Additions
      include_tasks: tasks/sshd/task.yml
      when: provision.security

    - name: Configure VPN
      when: provision.vpn
      include_tasks: tasks/vpn/task.yml

    # - name: Mailserver
    #   include_tasks: tasks/mail-server/task.yml
    #   when: provision.mailserver

    # - name: Configure VHosts
    #   include_tasks: tasks/vhosts/task.yml
    #   when: provision.vhosts

    # - name: Configure grafana
    #   when: provision.grafana
    #   include_tasks: tasks/grafana/task.yml

    # - name: Restart Services
    #   become: true
    #   ansible.builtin.systemd_service:
    #     name: "{{ item }}"
    #     state: restarted
    #   loop:
    #     - nginx
    #     - fail2ban
    #     - firewalld

    # - name: Restart system docker containers
    #   become: true
    #   ansible.builtin.command: docker container restart {{ item }}
    #   loop:
    #     - dns
    #     - mailserver
    #     - grafana
    #     - prometheus
    #     - loki
    #     - promtail
    #     - node_exporter

    - name: Configure K3s
      when: provision.k3s
      include_tasks: tasks/k3s/task.yml
