---
kind: IngressRouteTCP
apiVersion: traefik.io/v1alpha1
metadata:
  name: {{ .Release.Name }}-mail-submission-secure
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - ml-sub-secure
  routes:
    - match: HostSNI(`*`)
      services:
        - name: mail-docker-mailserver
          port: subs-proxy
          proxyProtocol:
            version: 2