# namespace: <string>
# rules:
#  - condition: "Host(`example.com`)"
#    service:
#      name: example-service
#      port: http
#
webfacade:
  storageSize: 2Gi
  image: nginx:1.31.2-alpine
  ports:
    - name: http
      containerPort: 80
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

dnsRecords: []
# - zone: example.com
#   name: example.com.
#   type: A
#   ipv4Address:
#      name: host-metadata
#      namespace: default
# - zone: example.com
#   name: mail
#   type: MX
#   mailServer: mail.example.com.
#   priority: 10
# - zone: example.com
#   name: www
#   type: CNAME
#   canonicalName: example.com.
# - zone: example.com
#   name: example.com.
#   type: NS
#   nameserver: ns1.example.com.