---
repositories:
  - name: bindy-charts
    url: https://Hobart2967.github.io/bindy-charts

releases:
  - name: bindy
    namespace: dns-system
    chart: bindy-charts/bindy
    version: 0.5.2
    installed: true
    values:
      - namespace: dns-system
        createNamespace: false