ingress:
  name: ark-2
service:
  type: LoadBalancer
  externalTrafficPolicy: Local
ports:
  rcon: 27021
  query: 27016
  game: 7779
serverConfig:
  arkServerName: "HarkEvolvedII"
  sessionName: "HarkEvolvedII"
arkServerPasswordSecretName: ark-server-password-ii
arkServerAdminPasswordSecretName: ark-server-password-ii
arkManager:
  extraConfig: ""