serverConfig:
  ports:
    rcon: 27021
    query: 27016
    game: 7779
    gameExt: 7780
  arkServerName: "HarkEvolvedII"
  sessionName: "HarkEvolvedII"
arkServerPasswordSecretName: ark-server-password-ii
arkServerAdminPasswordSecretName: ark-server-password-ii