{{- $portsList := list "query" "game" "game-ext" }}
{{- $release := .Release }}
{{ $values := .Values }}
{{- range $index := $portsList }}
---
kind: IngressRouteUDP
apiVersion: traefik.io/v1alpha1
metadata:
  name: {{ $release.Name }}-{{ $index }}
  namespace: {{ $release.Namespace }}
spec:
  entryPoints:
    - {{ $values.ingress.name }}-{{ $index }}
  routes:
    - services:
        - name: {{ $release.Name }}
          port: {{ $index }}
{{- end }}