- name: Check wether systemd service "k3s" exists
  become: true
  stat:
    path: /usr/local/bin/k3s
  register: service_status

- name: Install k3s with docker runtime configured
  become: true
  when: not service_status.stat.exists
  ansible.builtin.command: sh -c "curl -sfL https://get.k3s.io | sh -s - --docker --disable=traefik"

- name: Install socat to enable port forwarding
  apt:
    state: present
    update_cache: true
    pkg:
      - socat

- name: Create Directory - /etc/rancher/k3s/config.yaml.d
  become: true
  file:
    path: /etc/rancher/k3s/config.yaml.d
    state: directory
    mode: '0755'

- name: "Add traefik installation disablement"
  become: true
  copy:
    dest: /etc/rancher/k3s/config.yaml.d/disable-traefik.yaml
    content: |
      disable:
        - traefik