{{ $values := .Values }}
{{ $release := .Release }}

{{- range $values.rules }}
{{ $hostname := .hostname }}
{{ range $alias := .aliases -}}

{{ $resolvedAlias := include "hostname-by-dns" . }}

{{ $sanitized := replace "." "-" $resolvedAlias }}

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-from-{{ $sanitized }}
  namespace: {{ $values.namespace }}
spec:
  redirectRegex:
    regex: "^https://{{ $resolvedAlias }}(:?\\d*)/(.*)"
    replacement: "https://{{ include "hostname-by-dns" $hostname }}$1/$2"
{{ end }}

{{ end}}