databases:
  - resourceName: roundcube
    name: roundcube

users:
  - name: roundcube
    host: "%"
    databases:
      - name: roundcube
        host: "%"
        privileges:
        - "ALL PRIVILEGES"

