webfacade:
  storage:
    mountPath: /usr/share/nginx/html
rules:
- name: website
  hostname:
    name: www
    zone: engineer-marcoklein
  aliases:
  - name: "@"
    zone: engineer-marcoklein
  services:
    - name: website
      port: http
- name: webmail
  hostname:
    name: mail
    zone: engineer-marcoklein
  services:
    - name: webmail-roundcube
      port: http
