user:
  username: crowdsec-web-ui
  password: ""
  passwordSecretRef:
    name: ""
    key: ""

lapi:
  podSelector: k8s-app=crowdsec,type=lapi
  waitTimeoutSeconds: 180
  pollIntervalSeconds: 2

kubectl:
  image: bitnami/kubectl@sha256:95de17e6eb92da83a58c90a9df0c4cede634f898d2e6b92ea04f4a6ee6ace08d

job:
  backoffLimit: 2
  ttlSecondsAfterFinished: 300