{{- if .Values.blackboxExporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: blackbox-exporter
spec:
  replicas: {{ .Values.blackboxExporter.replicas }}
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
      - name: blackbox-exporter
        image: {{ .Values.blackboxExporter.image }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: web
          containerPort: {{ .Values.blackboxExporter.port }}
        args:
          - '--config.file=/config/blackbox.yml'
        resources:
          requests:
            memory: {{ .Values.blackboxExporter.resources.requests.memory }}
            cpu: {{ .Values.blackboxExporter.resources.requests.cpu }}
          limits:
            memory: {{ .Values.blackboxExporter.resources.limits.memory }}
            cpu: {{ .Values.blackboxExporter.resources.limits.cpu }}
        volumeMounts:
        - name: config
          mountPath: /config
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: web
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /-/healthy
            port: web
          initialDelaySeconds: 30
          periodSeconds: 15
      volumes:
      - name: config
        configMap:
          name: blackbox-config
{{- end }}
