{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Values.namespace }}
  labels:
    app: prometheus
spec:
  type: {{ .Values.prometheus.service.type }}
  selector:
    app: prometheus
  ports:
  - name: web
    port: {{ .Values.prometheus.service.port }}
    targetPort: {{ .Values.prometheus.port }}
---
{{- end }}
{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
  labels:
    app: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  selector:
    app: grafana
  ports:
  - name: web
    port: {{ .Values.grafana.service.port }}
    targetPort: {{ .Values.grafana.port }}
---
{{- end }}
{{- if .Values.loki.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ .Values.namespace }}
  labels:
    app: loki
spec:
  type: {{ .Values.loki.service.type }}
  selector:
    app: loki
  ports:
  - name: web
    port: {{ .Values.loki.service.port }}
    targetPort: {{ .Values.loki.port }}
---
{{- end }}
{{- if .Values.nodeExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: node-exporter
spec:
  type: {{ .Values.nodeExporter.service.type }}
  selector:
    app: node-exporter
  ports:
  - name: metrics
    port: {{ .Values.nodeExporter.service.port }}
    targetPort: {{ .Values.nodeExporter.port }}
---
{{- end }}
{{- if .Values.blackboxExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: blackbox-exporter
spec:
  type: {{ .Values.blackboxExporter.service.type }}
  selector:
    app: blackbox-exporter
  ports:
  - name: web
    port: {{ .Values.blackboxExporter.service.port }}
    targetPort: {{ .Values.blackboxExporter.port }}
---
{{- end }}
{{- if .Values.alertmanager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: {{ .Values.namespace }}
  labels:
    app: alertmanager
spec:
  type: {{ .Values.alertmanager.service.type }}
  selector:
    app: alertmanager
  ports:
  - name: web
    port: {{ .Values.alertmanager.service.port }}
    targetPort: {{ .Values.alertmanager.port }}
{{- end }}
