{{- range $secretName, $definition := .Values.secrets }}
{{- if index $definition "tags" }}
{{- range $tag := $definition.tags }}
{{- if $tag | contains "mailbox" }}
---
kind: Secret
apiVersion: v1
metadata:
  # Sanitize username, which is an email address for secret names
  name: {{ $definition.fields.username.value | replace "@" "-" | replace "." "-" }}
  annotations:
    hobart2967.github.io/mail-account: "true"
  namespace: sys-mail
data:
  username: {{ $definition.fields.username.value | b64enc | quote }}
  password: {{ $definition.fields.password.value | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}