---
{{- $hostNickname := include "hostNickname" (dict "Namespace" "default" "Name" "host-metadata") }}
{{- $domain := .Values.domainName }}
{{- if not (eq $hostNickname "tharja") }}
{{- $domain = (printf "%s.%s" $hostNickname .Values.domainName) }}
{{- end }}
apiVersion: bindy.firestoned.io/v1beta1
kind: NSRecord
metadata:
  name: {{ .Release.Name }}-primary
  namespace: {{ .Release.Namespace }}
  labels:
    dns-zone: {{ .Release.Name }}
spec:
  name: "@"
  nameserver: {{ .Values.primaryNameserver }}