---
apiVersion: bindy.firestoned.io/v1beta1
kind: NSRecord
metadata:
  name: {{ .Release.Name }}-secondary
  namespace: {{ .Release.Namespace }}
  labels:
    dns-zone: {{ .Values.domainName }}
spec:
  name: "@"
  nameserver: {{ .Values.secondaryNameserver }}