namespace: project-de-avsn
dnsRecords:
  - zone: avsn.de
    name: mail
    type: A
    ipv4Address: 192.168.178.95

  - zone: avsn.de
    name: mail
    type: MX
    priority: "10"
    mailServer: "mail.avsn.de."

  - zone: avsn.de
    name: www
    type: A
    ipv4Address: 192.168.178.95

  - zone: adventurespiele.net
    name: mail
    type: A
    ipv4Address: 192.168.178.95

  - zone: adventurespiele.net
    name: mail
    type: MX
    priority: "10"
    mailServer: "mail.adventurespiele.net."

  - zone: adventurespiele.net
    name: www
    type: A
    ipv4Address: 192.168.178.95
