- name: Create Blacklist refresh script
  become: true
  ansible.builtin.template:
    src: tasks/security/fail2ban/templates/etc/fail2ban/refresh-blacklist.sh.j2
    dest: /etc/fail2ban/refresh-blacklist.sh
    owner: root
    group: root
    mode: u=rwx,g=r,o=r

- name: Retrieve access data
  set_fact:
    fail2ban_report:
      sender_email: "{{ lookup('viczem.keepass.keepass', security.fail2ban.report.data, 'custom_properties', 'Sender') }}"
      destination_email: "{{ lookup('viczem.keepass.keepass', security.fail2ban.report.data, 'custom_properties', 'Destination') }}"
  when: security.fail2ban.report.active == True

- name: Retrieve access data
  set_fact:
    fail2ban_report:
      sender_email: "root@<fq-hostname>"
      destination_email: "root@localhost"
  when: security.fail2ban.report.active == False

- name: Configure Fail2ban
  become: true
  ansible.builtin.template:
    src: tasks/security/fail2ban/templates/etc/fail2ban/jail.conf.j2
    dest: /etc/fail2ban/jail.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Configure firewalld-ipset action
  become: true
  ansible.builtin.template:
    src: tasks/security/fail2ban/templates/etc/fail2ban/action.d/firewalld-ipset.conf.j2
    dest: /etc/fail2ban/action.d/firewalld-ipset.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: (Re)Start Fail2Ban
  become: true
  ansible.builtin.systemd_service:
    name: "fail2ban"
    state: restarted

# - name: Configure Logging for Fail2Ban
#   become: true
#   ansible.builtin.blockinfile:
#     path: /etc/monitoring/promtail/promtail-config.yml
#     append_newline: true
#     insertafter: "# Custom Log Files"
#     marker_begin: "BEGIN fail2ban-monitoring"
#     marker_end: "END fail2ban-monitoring"
#     block: |
#       # ----
#             - targets:
#                 - localhost
#               labels:
#                 job: fail2ban
#                 __path__: /var/log/fail2ban.log*

# - name: Restart promtail
#   become: true
#   ansible.builtin.command: docker compose restart promtail
#   args:
#     chdir: /etc/monitoring