---
releases:
  - name: website
    chart: ../../../helm/website
    namespace: project-engineer-marcoklein
    createNamespace: true
    values:
      - ./values/website.yaml
      - ./values/dns.yaml.gotmpl