serverConfig:
  motd: "Willkommen auf dem avsn.de Minecraft Server!"
  serverName: "Avsn.de Minecraft Server"
  texturePack: https://www.adventurespiele.net/Downloads/Sonstiges/ChromaHills.zip
  rconPassword:
    secretRef:
      name: de-avsn-maps
      key: password
  backupModes:
    - server-data
    - Marktwelt
    - flodders
    - flodders_end
    - flodders_nether
    - masamaje
    - masamaje_nether
    - plugin-jars
  knownPlayers:
    - Hobart2967
    - avsn-Nikki
    - Ariggeldiggel
    - Corsazicke87
  plugins:
    - name: AncientGates
      source: spigot
      args:
        id: 6583
        version: 542512 # 2.7.1
    - name: AutoBackup
      source: spigot
      args:
        id: 88209
        version: 384361 # 1.2.1
    - name: BKCommonLib
      source: spigot
      args:
        id: 39590
        version: 559399 # 1.21.1-v1
    - name: Brewery
      source: spigot
      args:
        id: 3082
        version: 369519 # v3.0
    - name: Chairs
      source: curl
      args:
        version: 5.1
        url: https://dev.bukkit.org/projects/chairsreloaded/files/2725118/download
    - name: Dynmap
      source: curl
      args:
        url: https://mediafilez.forgecdn.net/files/4632/182/Dynmap-3.6-spigot.jar
        version: v3.6-beta-2
    - name: EssentialsX
      source: curl
      args:
        version: 2.19.4
        url: https://github.com/EssentialsX/Essentials/releases/download/2.19.4/EssentialsX-2.19.4.jar
    - name: EssentialsXAntiBuild
      source: curl
      args:
        version: 2.19.4
        url: https://github.com/EssentialsX/Essentials/releases/download/2.19.4/EssentialsXAntiBuild-2.19.4.jar
    - name: EssentialsXChat
      source: curl
      args:
        version: 2.19.4
        url: https://github.com/EssentialsX/Essentials/releases/download/2.19.4/EssentialsXChat-2.19.4.jar
    - name: EssentialsXSpawn
      source: curl
      args:
        version: 2.19.4
        url: https://github.com/EssentialsX/Essentials/releases/download/2.19.4/EssentialsXSpawn-2.19.4.jar
    - name: floodgate-plugin
      source: curl
      args:
        version: 2.2.2
        url: https://download.geysermc.org/v2/projects/floodgate/versions/2.2.2/builds/latest/downloads/spigot
    - name: geyser
      source: curl
      args:
        version: 2.1.1
        url: https://download.geysermc.org/v2/projects/geyser/versions/2.1.1/builds/latest/downloads/spigot
    - name: LuckPerms
      source: spigot
      args:
        id: 28140
        version: 544174 # 5.4.131
    - name: Minepacks
      source: spigot
      args:
        id: 19286
        version: 545752 # 2.4.31.5
    - name: Multiverse-Core
      source: curl
      args:
        version: 4.3.9
        url: https://github.com/Multiverse/Multiverse-Core/releases/download/4.3.9/multiverse-core-4.3.9.jar
    - name: Multiverse-NetherPortals
      source: curl
      args:
        version: 4.2.3
        url: https://github.com/Multiverse/Multiverse-NetherPortals/releases/download/4.2.3/multiverse-netherportals-4.2.3.jar
    - name: Multiverse-Portals
      source: curl
      args:
        version: 4.2.3
        url: https://github.com/Multiverse/Multiverse-Portals/releases/download/4.2.3/multiverse-portals-4.2.3.jar
    - name: PluginConstructorAPI
      source: curl
      args:
        version: 1.0.52
        url: https://github.com/ZombieStriker/PluginConstructorAPI/releases/download/v1.0.52/PluginConstructorAPI.jar
    - name: ProtocolLib
      source: spigot
      args:
        id: 1997
        version: 496322 # 5.0.0
    - name: ServerListPlus-3.5.0-Universal
      source: spigot
      args:
        id: 241
        version: 501840 # 3.5.0
    - name: SignLink
      source: spigot
      args:
        id: 39593
        version: 501863 # 1.20.1-v1
    - name: SmoothSleep
      source: spigot
      args:
        id: 32043
        version: 396611 # 2.11.2
    - name: TpWolfv1.6
      source: spigot
      args:
        id: 62355
        version: 248200 # 1.6
    - name: TrainCarts
      source: spigot
      args:
        id: 39592
        version: 501859 # 1.20.1-v1
    - name: Vault
      source: spigot
      args:
        id: 34315
        version: 344916 # 1.7.3
    - name: WorldBorder
      source: spigot
      args:
        id: 60905
        version: 240474 # 1.9.0
    - name: WorldEdit
      source: curl
      args:
        id: 7.2.15
        url: https://dev.bukkit.org/projects/worldedit/files/4586220/download
    - name: WorldGuardExtraFlags
      source: spigot
      args:
        id: 4823
        version: 326911 # 4.1.4
    - name: WorldGuard
      source: curl
      args:
        id: 7.0.9
        url: https://mediafilez.forgecdn.net/files/4675/318/worldguard-bukkit-7.0.9-dist.jar